#!/usr/bin/env python3
"""Regenerate every benchmark case's diff.patch from its recorded before-state.

Each case directory may contain a `_before/` tree holding the pre-change
version of exactly the files the change touches:

    benchmark/cases/<case-id>/
        _before/src/foo.rs      <- pre-change (empty file = the change adds it)
        repository/src/foo.rs   <- post-change, what the agent reviews
        diff.patch              <- generated by this script

`_before/` sits outside `repository/`, which is the agent's sandbox root, so it
is never visible to a reviewer. Keeping it in the repository makes each diff
reproducible and auditable instead of hand-written.

Usage:
    python scripts/make_diffs.py [--check]

    --check  verify the committed diffs match what would be generated,
             and exit non-zero if any differ. Intended for CI and for
             confirming a frozen benchmark has not drifted.
"""

import argparse
import difflib
import io
import pathlib
import sys

CASES = pathlib.Path("benchmark/cases")


def read_lines(path: pathlib.Path) -> list[str]:
    if not path.exists():
        return []
    text = io.open(path, encoding="utf-8", newline="").read().replace("\r\n", "\n")
    return text.splitlines(keepends=True)


def build_diff(case_dir: pathlib.Path) -> str | None:
    before_root = case_dir / "_before"
    repo_root = case_dir / "repository"
    if not before_root.is_dir():
        return None

    chunks: list[str] = []
    for before_file in sorted(p for p in before_root.rglob("*") if p.is_file()):
        rel = before_file.relative_to(before_root).as_posix()
        after_file = repo_root / rel

        before = read_lines(before_file)
        after = read_lines(after_file)

        # An empty before-file means the change introduces the file.
        from_label = "/dev/null" if not before else f"a/{rel}"
        to_label = f"b/{rel}"

        diff = difflib.unified_diff(
            before, after, fromfile=from_label, tofile=to_label, n=3
        )
        chunk = "".join(diff)
        if chunk:
            if not chunk.endswith("\n"):
                chunk += "\n"
            chunks.append(chunk)

    return "".join(chunks)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    if not CASES.is_dir():
        print(f"no benchmark directory at {CASES}", file=sys.stderr)
        return 2

    drifted, written, skipped = [], [], []

    for case_dir in sorted(p for p in CASES.iterdir() if p.is_dir()):
        generated = build_diff(case_dir)
        if generated is None:
            skipped.append(case_dir.name)
            continue

        target = case_dir / "diff.patch"
        current = (
            io.open(target, encoding="utf-8", newline="").read().replace("\r\n", "\n")
            if target.exists()
            else None
        )

        if args.check:
            if current != generated:
                drifted.append(case_dir.name)
        elif current != generated:
            io.open(target, "w", encoding="utf-8", newline="\n").write(generated)
            written.append(case_dir.name)

    if skipped:
        print(f"no _before/ tree (diff left as-is): {', '.join(skipped)}")

    if args.check:
        if drifted:
            print("DIFF DRIFT in: " + ", ".join(drifted), file=sys.stderr)
            print(
                "diff.patch no longer matches _before/ vs repository/. "
                "Either the case changed or the diff was hand-edited.",
                file=sys.stderr,
            )
            return 1
        print("all diffs match their before/after trees")
        return 0

    print(f"regenerated {len(written)} diff(s)" + (": " + ", ".join(written) if written else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
